# Generated by Django 5.2.6 on 2025-10-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("civilian", "0002_registration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginSubmission",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
