# Generated by Django 5.2.7 on 2025-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilian', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/images/'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='issues/videos/'),
        ),
    ]
