# Generated by Django 5.2.7 on 2025-10-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilian', '0005_issuereport_image_issuereport_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
