# Generated by Django 5.2.7 on 2025-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilian', '0006_issuereport_status_issuereport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
